2021-02-02 17:55:04,200 INFO    MainThread:473 [wandb_setup.py:_flush():70] setting env: {}
2021-02-02 17:55:04,200 INFO    MainThread:473 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-02-02 17:55:04,200 INFO    MainThread:473 [wandb_setup.py:_flush():70] setting login settings: {}
2021-02-02 17:55:04,200 INFO    MainThread:473 [wandb_setup.py:_flush():70] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f2650f892e8>
2021-02-02 17:55:04,202 INFO    MainThread:473 [wandb_init.py:_log_setup():318] Logging user logs to /content/instance-video-colorization/wandb/run-20210202_175504-3b0yc1xc/logs/debug.log
2021-02-02 17:55:04,202 INFO    MainThread:473 [wandb_init.py:_log_setup():319] Logging internal logs to /content/instance-video-colorization/wandb/run-20210202_175504-3b0yc1xc/logs/debug-internal.log
2021-02-02 17:55:06,700 INFO    MainThread:473 [wandb_run.py:_console_start():1399] atexit reg
2021-02-02 17:55:06,700 INFO    MainThread:473 [wandb_run.py:_redirect():1262] redirect: SettingsConsole.WRAP
2021-02-02 17:55:06,702 INFO    MainThread:473 [wandb_run.py:_redirect():1297] Wrapping output streams.
2021-02-02 17:55:06,702 INFO    MainThread:473 [wandb_run.py:_redirect():1313] Redirects installed.
2021-02-02 17:55:06,709 INFO    MainThread:473 [wandb_init.py:_pause_backend():239] pausing backend
2021-02-02 17:55:06,721 INFO    MainThread:473 [wandb_init.py:_resume_backend():244] resuming backend
2021-02-02 17:55:06,723 INFO    MainThread:473 [wandb_init.py:_pause_backend():239] pausing backend
2021-02-02 17:55:06,728 INFO    MainThread:473 [wandb_init.py:_resume_backend():244] resuming backend
2021-02-02 17:55:06,917 INFO    MainThread:473 [wandb_init.py:_pause_backend():239] pausing backend
2021-02-02 17:55:06,929 INFO    MainThread:473 [wandb_init.py:_resume_backend():244] resuming backend
2021-02-02 17:55:28,304 INFO    MainThread:473 [wandb_init.py:_pause_backend():239] pausing backend
2021-02-02 17:55:52,072 INFO    MainThread:473 [wandb_run.py:_atexit_cleanup():1369] got exitcode: 0
2021-02-02 17:55:52,072 INFO    MainThread:473 [wandb_run.py:_restore():1341] restore
2021-02-02 17:55:52,286 INFO    MainThread:473 [wandb_run.py:_wait_for_finish():1492] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 868
  total_bytes: 868
}

2021-02-02 17:55:54,299 INFO    MainThread:473 [wandb_run.py:_wait_for_finish():1492] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9021
  total_bytes: 9021
}

2021-02-02 17:55:55,586 INFO    MainThread:473 [wandb_run.py:_show_files():1714] logging synced files
2021-02-02 17:55:55,590 INFO    MainThread:473 [internal.py:handle_exit():156] Internal process exited
