2021-02-02 17:51:08,351 INFO    MainThread:240 [wandb_setup.py:_flush():70] setting env: {}
2021-02-02 17:51:08,351 INFO    MainThread:240 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-02-02 17:51:08,351 INFO    MainThread:240 [wandb_setup.py:_flush():70] setting login settings: {}
2021-02-02 17:51:08,351 INFO    MainThread:240 [wandb_setup.py:_flush():70] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f7b8fb477b8>
2021-02-02 17:51:08,352 INFO    MainThread:240 [wandb_init.py:_log_setup():318] Logging user logs to /content/instance-video-colorization/wandb/run-20210202_175108-3qe6npbm/logs/debug.log
2021-02-02 17:51:08,352 INFO    MainThread:240 [wandb_init.py:_log_setup():319] Logging internal logs to /content/instance-video-colorization/wandb/run-20210202_175108-3qe6npbm/logs/debug-internal.log
2021-02-02 17:51:10,806 INFO    MainThread:240 [wandb_run.py:_console_start():1399] atexit reg
2021-02-02 17:51:10,806 INFO    MainThread:240 [wandb_run.py:_redirect():1262] redirect: SettingsConsole.WRAP
2021-02-02 17:51:10,808 INFO    MainThread:240 [wandb_run.py:_redirect():1297] Wrapping output streams.
2021-02-02 17:51:10,808 INFO    MainThread:240 [wandb_run.py:_redirect():1313] Redirects installed.
2021-02-02 17:51:10,812 INFO    MainThread:240 [wandb_init.py:_pause_backend():239] pausing backend
2021-02-02 17:51:10,816 INFO    MainThread:240 [wandb_init.py:_resume_backend():244] resuming backend
2021-02-02 17:51:10,819 INFO    MainThread:240 [wandb_init.py:_pause_backend():239] pausing backend
2021-02-02 17:51:10,833 INFO    MainThread:240 [wandb_init.py:_resume_backend():244] resuming backend
2021-02-02 17:51:11,033 INFO    MainThread:240 [wandb_init.py:_pause_backend():239] pausing backend
2021-02-02 17:51:11,041 INFO    MainThread:240 [wandb_init.py:_resume_backend():244] resuming backend
2021-02-02 17:51:26,228 INFO    MainThread:240 [wandb_init.py:_pause_backend():239] pausing backend
2021-02-02 17:51:55,055 INFO    MainThread:240 [wandb_run.py:_atexit_cleanup():1369] got exitcode: 0
2021-02-02 17:51:55,056 INFO    MainThread:240 [wandb_run.py:_restore():1341] restore
2021-02-02 17:51:55,282 INFO    MainThread:240 [wandb_run.py:_wait_for_finish():1492] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 868
  total_bytes: 868
}

2021-02-02 17:51:57,291 INFO    MainThread:240 [wandb_run.py:_wait_for_finish():1492] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9021
  total_bytes: 9021
}

2021-02-02 17:51:58,589 INFO    MainThread:240 [wandb_run.py:_show_files():1714] logging synced files
2021-02-02 17:51:58,593 INFO    MainThread:240 [internal.py:handle_exit():156] Internal process exited
